version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
      
  adminer:
    image: adminer
    container_name: adminer-local
    restart: unless-stopped
    ports:
      - "8080:8080"
